### PR TITLE
Fix map zoom performance on multiple metric changes: fix onMapMove function event listener removing

### LINKED ISSUE #282: Map becomes less responsive after switching metrics
The map becomes progressively slower to zoom as you switch metrics. It becomes obvious after switching 10 or so times.

### PR DESCRIPTION
**Pull request by torosyaneric**
Resolves #282

### CODE REVIEW

File: frontend/src/components/Map/Map.js [hunk 1]
```diff
@@ -239,7 +244,7 @@ function Map({
 
       // map click event
       if (onMapClickRef.current) {
-        map.current.off('mouseleave', layerId, onMapClickRef.current)
+        map.current.off('mouseleave', prevLayerId, onMapClickRef.current)
```
Comment (justinanderson) [inline frontend/src/components/Map/Map.js:247]: Shouldn't this be `'click'`, not `'mouseleave'`?

File: frontend/src/components/Map/Map.js [hunk 2]
```diff
@@ -395,16 +402,23 @@ function Map({
...
+      map.current.off('mousemove', onAllMapMouseMoveRef.current)
+
       if (layerIds.length) {
         layerIds.forEach(id => {
           const layer = map.current.getLayer(id)
           if (layer) {
+            map.current.off('mousemove', id, onMouseMoveRef.current)
+            map.current.off('mouseleave', id, onMouseLeaveRef.current)
+            map.current.off('mouseleave', id, onMapMoveRef.current)
+            map.current.off('mouseleave', id, onMapClickRef.current)
```
Comment (justinanderson) [inline frontend/src/components/Map/Map.js:414]: These shouldn't all be `'mouseleave'`, right?

**Review by justinanderson — CHANGES_REQUESTED** [review]
@torosyaneric This definitely fixes the slowdown I was seeing.

There are a few of what I think are typo'd event names. There's no obvious negative effect to them, but it'd be good to get them right.

**Review by justinanderson — APPROVED** [review]
